# Generated by Django 2.2.3 on 2019-07-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragent',
            options={'ordering': ['browser']},
        ),
    ]
