# Generated by Django 2.2.3 on 2019-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoof', '0002_auto_20190717_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='ip',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
