# Generated by Django 2.2.3 on 2019-07-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoof', '0003_auto_20190718_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='proxy_user',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
