# Generated by Django 2.2.3 on 2019-07-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0002_auto_20190712_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresults',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
