# Generated by Django 2.2.3 on 2019-07-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0004_userconfig_time_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresults',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
    ]
