# Generated by Django 2.2.3 on 2019-07-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoof', '0002_auto_20190717_1946'),
        ('serp', '0005_auto_20190715_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='user_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoof.UserAgent'),
        ),
    ]
