# Generated by Django 2.2.3 on 2019-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0006_userconfig_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='use_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
